language: python
python:
  - 3.5

services:
  - mongodb
  - rabbitmq


before_install:
  - sudo apt-get install lxd -y


install: 
  - pip install -r requirements.txt



# command to run tests
script: 
  - cd pirus
  - make test


branches:
  only:
    - master
