language: python
python: 3.5
dist: trusty



before_install:
  - sudo add-apt-repository ppa:ubuntu-lxc/lxd-stable -y
  - sudo apt-get update
  - sudo apt-get install lxd -y



services:
  - mongodb
  - rabbitmq




install: 
  - pip install -r requirements.txt




script: 
  - cd pirus
  - sudo make test


branches:
  only:
    - master
