site_name: Pirus
pages:
- Home: index.md
- About: about.md
- Developer Guide :
  - Welcom guide : dev/welcom.md
  - Model : dev/model.md
  - Api Rest : dev/restapi.md
theme: readthedocs
extra_css: [extra.css]